<a href="https://colab.research.google.com/github/spandana1320/AIML/blob/main/assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
input=[1,2,3]
weights=[0.2,0.3,-0.5]
bias=2
output=input[0]*weights[0]+input[1]*weights[1]+input[2]*weights[2]+bias
print(output)

1.3


In [ ]:
input=[0.4,0.3,1,0.8]
weight1=[0.3,0.2,0.1,0.4]
weight2=[0.4,0.1,-0.1,0.2]
weight3=[0.2,-0.2,-0.1,0.8]
bias1=0.5
bias2=0.3
bias3=0.6
output=[input[0]*weight1[0]+input[1]*weight1[1]+input[2]*weight1[2]+input[3]*weight1[3]+bias1,
       input[0]*weight2[0]+input[1]*weight2[1]+input[2]*weight2[2]+input[3]*weight2[3]+bias2,
       input[0]*weight3[0]+input[1]*weight3[1]+input[2]*weight2[2]+input[3]*weight3[3]+bias3]
print(output)



[1.1, 0.55, 1.1600000000000001]


In [ ]:
import numpy as np
inputs=np.array([0.4,0.3,1,0.8])
weights= np.array([
    [0.3,0.2,0.1,0.4],
         [0.4,0.1,-0.1,0.2],
               [0.2,-0.2,-0.1,0.8]
               ])
biases=np.array([0.5,0.3,0.6])
output=np.dot(weights,inputs)+biases
print(output)

[1.1  0.55 1.16]


In [ ]:
import numpy as np
def relu(x):
  return np.maximum(0,x)
  inputs=np.array([0.4,0.3,1,0.8])
  weights= np.array([
      [0.3,0.2,0.1,0.4],
           [0.4,0.1,-0.1,0.2],
                 [0.2,-0.2,-0.1,0.8]
                 ])
biases=np.array([0.5,0.3,0.6])
output=np.dot(weights,inputs)+biases
output=relu(output)
print(output)

[1.1  0.55 1.16]


In [ ]:
import numpy as np
def sigmoid(x):
  return 1/(1+np.exp(-x))
    def relu(x):
        return np.maximum(0,x)
        inputs=np.array([0.4,0.3,1,0.8])
        weights= np.array([
            [0.3,0.2,0.1,0.4],
                 [0.4,0.1,-0.1,0.2],
                       [0.2,-0.2,-0.1,0.8]
                       ])
biases=np.array([0.5,0.3,0.6])
output=np.dot(weights,inputs)+biases
output1=relu(output)
print(output1)
output2=sigmoid(output)
print(output2)

IndentationError: unexpected indent (<ipython-input-10-18907d6057ac>, line 4)

In [ ]:
import numpy as np
def sigmoid(x):
  return 1/(1+np.exp(-x))
def relu(x):
        return np.maximum(0,x)
        inputs=np.array([0.4,0.3,1,0.8])
        weights= np.array([
            [0.3,0.2,0.1,0.4],
                 [0.4,0.1,-0.1,0.2],
                       [0.2,-0.2,-0.1,0.8]
                       ])
biases=np.array([0.5,0.3,0.6])
output=np.dot(weights,inputs)+biases
output1=relu(output)
print(output1)
output2=sigmoid(output)
print(output2)

[1.1  0.55 1.16]
[0.75026011 0.63413559 0.76133271]
